import Head from 'next/head';
import Layout from '../components/Layout';
import useCountry from '../hook/useCountry';
import useSearch from '../hook/useSearch';

import Search from '../components/Search';

export default function Home() {
  const {
    isLoading,
    countryData,
    regionList
  } = useCountry()

  const {inputSearch, onChangeSearch} = useSearch();
  
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className='mt-5 flex w-full justify-between'>
          <Search/>

        </div>
      </Layout>

    </div>
  )
}
